"""empty message

Revision ID: c16f580e4741
Revises: 
Create Date: 2022-01-12 11:44:18.971008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16f580e4741'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pautas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('names', sa.String(length=200), nullable=True),
    sa.Column('mother_lastname', sa.String(length=200), nullable=True),
    sa.Column('father_lastname', sa.String(length=200), nullable=True),
    sa.Column('rut', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('requerimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(length=500), nullable=True),
    sa.Column('seleccion', sa.Boolean(), nullable=True),
    sa.Column('pauta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pauta_id'], ['pautas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.create_table('supervisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('content', sa.Text(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('supervision_id', sa.Integer(), nullable=True),
    sa.Column('requerimiento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requerimiento_id'], ['requerimientos.id'], ),
    sa.ForeignKeyConstraint(['supervision_id'], ['supervisiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados')
    op.drop_table('supervisiones')
    op.drop_table('roles_users')
    op.drop_table('requerimientos')
    op.drop_table('profiles')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('pautas')
    # ### end Alembic commands ###
